// Canned games used by mock/demo mode (MOCK_AI=1) — no API key required.

export function build2D() {
  return {
    gameType: '2d',
    engine: 'vanilla',
    title: 'Aurora Runner',
    description: 'Demo 2D auto-runner generated by mock AI. Time your jumps, dodge the red pillars.',
    genre: 'arcade',
    files: [
      {
        path: 'index.html',
        content: `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Aurora Runner</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}html,body{height:100%;background:#07070c;overflow:hidden;
font-family:system-ui,sans-serif;display:flex;align-items:center;justify-content:center}
#w{position:relative}canvas{display:block;border-radius:12px;box-shadow:0 0 60px rgba(201,168,76,.2)}
#s{position:absolute;top:12px;left:16px;color:#c9a84c;letter-spacing:.14em;text-transform:uppercase;font-size:13px}
#g{position:absolute;inset:0;display:none;flex-direction:column;align-items:center;justify-content:center;
background:rgba(7,7,12,.85);border-radius:12px;color:#e8e6e0;gap:8px}
#g h1{color:#c9a84c;font-size:26px;letter-spacing:.05em}
#g button{margin-top:6px;padding:8px 20px;border:none;border-radius:6px;cursor:pointer;
background:linear-gradient(#e8c97a,#c9a84c);color:#111;font-weight:600}
</style></head><body>
<div id="w"><canvas id="c" width="800" height="400"></canvas>
<div id="s">Score <b id="sc">0</b></div>
<div id="g"><h1>GAME OVER</h1><p id="fs"></p><button onclick="reset()">Retry</button></div></div>
<script src="game.js"></script></body></html>`,
      },
      {
        path: 'game.js',
        content: `// Aurora Runner — mock-generated demo
const c=document.getElementById('c'),x=c.getContext('2d');
let player,obstacles,score,speed,dead,t,stars;
const G=340;
function reset(){player={y:0,vy:0,onGround:true};obstacles=[];score=0;speed=5;dead=false;t=0;
stars=Array.from({length:60},()=>({x:Math.random()*800,y:Math.random()*400,r:Math.random()*1.6+.3,s:Math.random()*.4+.1}));
document.getElementById('g').style.display='none';document.getElementById('sc').textContent='0';}
function jump(){if(player.onGround){player.vy=-11;player.onGround=false;}}
document.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();
 if(dead)reset();else jump();}});
c.addEventListener('click',()=>{if(dead)reset();else jump();});
function step(){
  if(dead)return;
  player.vy+=0.62;player.y+=player.vy;
  if(player.y>=0){player.y=0;player.vy=0;player.onGround=true;}
  t++;
  if(t%Math.max(28,60-speed*2)===0)obstacles.push({x:820,h:Math.random()*60+30});
  obstacles.forEach(o=>o.x-=speed);
  obstacles=obstacles.filter(o=>o.x>-60);
  const px=110,pw=34,ph=34,py=G-30+player.y;
  for(const o of obstacles){
    const ox=o.x,oy=G-30-o.h,ow=26,oh=o.h;
    if(px<ox+ow&&px+pw>ox&&py<oy+oh&&py+ph>oy){dead=true;
      document.getElementById('fs').textContent='Score: '+Math.floor(score);
      document.getElementById('g').style.display='flex';}
  }
  score+=0.1;speed=Math.min(11,speed+0.0015);
  document.getElementById('sc').textContent=Math.floor(score);
}
function draw(){
  const grd=x.createLinearGradient(0,0,0,400);grd.addColorStop(0,'#12121c');grd.addColorStop(1,'#07070c');
  x.fillStyle=grd;x.fillRect(0,0,800,400);
  stars.forEach(s=>{s.x-=s.s;if(s.x<0)s.x=800;x.fillStyle='rgba(201,168,76,'+(0.25+s.r/3)+')';
    x.beginPath();x.arc(s.x,s.y,s.r,0,7);x.fill();});
  x.fillStyle='#1c1c28';x.fillRect(0,G-30,800,400-G+30);
  x.strokeStyle='rgba(201,168,76,.5)';x.beginPath();x.moveTo(0,G-30);x.lineTo(800,G-30);x.stroke();
  x.shadowColor='#c9a84c';x.shadowBlur=18;x.fillStyle='#e8c97a';
  x.fillRect(110,G-30+player.y,34,34);x.shadowBlur=0;
  x.fillStyle='#f87171';obstacles.forEach(o=>{x.shadowColor='#f87171';x.shadowBlur=12;
    x.fillRect(o.x,G-30-o.h,26,o.h);x.shadowBlur=0;});
  if(!dead){step();}
  requestAnimationFrame(draw);
}
reset();draw();`,
      },
    ],
    mainFile: 'index.html',
    controls: 'Space / Arrow Up / Click to jump',
    features: ['Auto-runner gameplay', 'Parallax starfield', 'Progressive speed', 'Glow rendering'],
    thinking: 'Mock mode: self-contained 2D auto-runner to demonstrate the studio pipeline without an API key.',
  };
}

export function build3D() {
  return {
    gameType: '3d',
    engine: 'threejs',
    title: 'Orbital Drift',
    description: 'Demo 3D game generated by mock AI. Steer your ship through glowing neon rings.',
    genre: 'adventure',
    files: [
      {
        path: 'index.html',
        content: `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Orbital Drift</title>
<style>*{margin:0;padding:0;box-sizing:border-box}html,body{height:100%;overflow:hidden;background:#04040a;
font-family:system-ui,sans-serif}#hud{position:fixed;top:14px;left:18px;color:#c9a84c;letter-spacing:.14em;
text-transform:uppercase;font-size:13px;z-index:10}#msg{position:fixed;inset:0;display:flex;align-items:center;
justify-content:center;color:#e8e6e0;font-size:15px;text-align:center;z-index:10;pointer-events:none;
text-shadow:0 2px 20px #000}</style></head>
<body><div id="hud">Score <b id="s">0</b></div>
<div id="msg">Fly through the glowing rings — mouse to steer</div>
<script src="https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js"></script>
<script src="game.js"></script></body></html>`,
      },
      {
        path: 'game.js',
        content: `// Orbital Drift — mock-generated 3D demo
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x04040a,0.012);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,0.1,400);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);
renderer.setClearColor(0x04040a);document.body.appendChild(renderer.domElement);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();
 renderer.setSize(innerWidth,innerHeight);});
let mx=0,my=0;addEventListener('mousemove',e=>{mx=(e.clientX/innerWidth-.5)*2;my=-(e.clientY/innerHeight-.5)*2;});
const stars=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',
 new THREE.Float32BufferAttribute(Array.from({length:2500},()=>(Math.random()-.5)*400),3)),
 new THREE.PointsMaterial({color:0xc9a84c,size:.7,transparent:true,opacity:.75}));
scene.add(stars);
scene.add(new THREE.AmbientLight(0xffffff,.5));
const key=new THREE.PointLight(0xc9a84c,2,120);scene.add(key);
const ship=new THREE.Mesh(new THREE.ConeGeometry(.7,2,6),
 new THREE.MeshStandardMaterial({color:0xe8c97a,emissive:0xc9a84c,emissiveIntensity:.5,metalness:.6,roughness:.3}));
ship.rotation.x=Math.PI/2;scene.add(ship);
let score=0;const rings=[];
function spawnRing(){const r=new THREE.Mesh(new THREE.TorusGeometry(3.4,.18,8,40),
 new THREE.MeshStandardMaterial({color:0x60a5fa,emissive:0x3b82f6,emissiveIntensity:.9}));
 r.position.set((Math.random()-.5)*26,(Math.random()-.5)*18,-260-Math.random()*80);
 r.userData.passed=false;scene.add(r);rings.push(r);}
for(let i=0;i<7;i++)spawnRing();
let pos=new THREE.Vector3(0,0,0),vel=0;
function animate(){
 requestAnimationFrame(animate);
 pos.z-=0.9+vel*0.02;vel=Math.min(1.6,vel+0.0006);
 pos.x+=((mx*7)-pos.x)*0.045;pos.y+=((my*5)-pos.y)*0.045;
 ship.position.copy(pos);ship.rotation.z=-mx*0.5;
 stars.position.z=pos.z;
 rings.forEach(r=>{
  if(!r.userData.passed&&r.position.z>pos.z){r.userData.passed=true;score+=10;
   document.getElementById('s').textContent=score;
   document.getElementById('msg').style.opacity=Math.max(0,1-score/50);}
  if(r.position.z>pos.z+30){r.position.set((Math.random()-.5)*26,(Math.random()-.5)*18,
   pos.z-260-Math.random()*90);r.userData.passed=false;}
  r.rotation.z+=0.01;r.rotation.x+=0.006;
 });
 key.position.set(pos.x,pos.y+3,pos.z-8);
 camera.position.set(pos.x*0.35,pos.y*0.35+1.4,pos.z+9);
 camera.lookAt(pos.x,pos.y,pos.z-20);
 renderer.render(scene,camera);
}
animate();`,
      },
    ],
    mainFile: 'index.html',
    controls: 'Move mouse to steer the ship',
    features: ['Three.js WebGL', 'Neon rings', 'Starfield', 'Emissive lighting'],
    thinking: 'Mock mode: self-contained Three.js game to demonstrate the 3D pipeline without an API key.',
  };
}
